version: '3.4'
services:
  api:
    container_name: directus_extension_ai_hk
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '8061:8055'
    volumes:
      - ./uploads:/app/uploads
      - api_database:/app/database
    env_file:
      - ./.env
    environment:
      PORT: 8055
volumes:
  api_uploads:
  api_database:
